### ISSUE TITLE
Visual Studio SDF file is 35MB!

### ISSUE THREAD

**Issue by sbates130272** [waywardgeek/infnoise#57]
Hi

For some reason the VS .sdf file is included in the repo and its 35MB in size. Seems like that could be avoided?

Stephen

**Comment by manuel-domke** [comment]
Yes. Let's remove it. According to Stackoverflow its not needed in any way: 

https://stackoverflow.com/questions/7706984/visual-studio-2010-c-project-remove-sdf-file

I also recognized it but never checked as I'm not so familiar with the Visual Studio; it's years ago since I used it last time, but I want to merge the latest changes and recompile the Windows binary soon.

**Comment by manuel-domke** [comment]
Thanks!
